- name: install nginx
  yum: 
    name:
      - nginx
    state: present
   
- name: start nginx
  systemd:
    name: nginx
    state: started
  
- name: create directory
  file:
    path: /var/www/html
    state: directory
    owner: root
    recurse: yes
    code: 0755

- name: index
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

